//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminBookTable
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string Day { get; set; }
        public string Hours { get; set; }
        public string PersonNo { get; set; }
        public string UserId { get; set; }
        public string Status { get; set; }
    }
}
